name: forcontu s1 drupal build
on: [push]

permissions:
  statuses: write
  pull-requests: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set commit status to pending
        uses: ouzi-dev/commit-status-updater@v2
        with:
          url: http://sb1.arnicole.training.forcontu.com/
          description: "Drupal / composer build status"
          name: "drupal build"
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
      - name: executing remote ssh commands using password
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |

            echo 'changing to right directory';
            cd public_html/sb/sb1

            echo 'fetching latest changes'
            git fetch --all --prune
            if [ $? -ne 0 ]; then exit 1; fi

            echo 'unlocking settings.php file'
            chmod u+w web/sites/default
            chmod u+w web/sites/default/settings.php
            if [ $? -ne 0 ]; then exit 1; fi

            echo 'resetting to HEAD'
            git reset --hard origin/main
            if [ $? -ne 0 ]; then exit 1; fi

            echo 'locking settings.php file'
            chmod u-w web/sites/default/settings.php
            chmod u-w web/sites/default
            if [ $? -ne 0 ]; then exit 1; fi

            echo 'running composer install';
            composer install
            if [ $? -ne 0 ]; then exit 1; fi

            echo 'getting drush status';
            vendor/bin/drush st;
            if [ $? -ne 0 ]; then exit 1; fi

            echo 'clearing caches';
            vendor/bin/drush cr
            if [ $? -ne 0 ]; then exit 1; fi

            echo 'updating db';
            vendor/bin/drush updb
            if [ $? -ne 0 ]; then exit 1; fi

            echo 'importing config';
            vendor/bin/drush cim -y
            if [ $? -ne 0 ]; then exit 1; fi

      - name: Update commit status at the end
        uses: ouzi-dev/commit-status-updater@v2
        if: always()
        with:
          status: "${{ job.status }}"
          url: http://sb1.arnicole.training.forcontu.com/
          description: "Drupal / composer build status"
          name: "drupal build"
